# .github/workflows/all_tests_on_push.yml
name: Minden Teszt (Push)

on:
  push:
    branches: [ main ]

jobs:
  run_all_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Kód letöltése
      uses: actions/checkout@v4

    - name: Python környezet beállítása
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Függőségek telepítése
      run: pip install pytest

    - name: Unit és Integrációs tesztek futtatása
      # A sima 'pytest' parancs futtatja az összes tesztet a test_*.py fájlokban
      run: pytest
