- name: Python telepítése
  uses: actions/setup-python@v5
  with:
    python-version: '3.x'

- name: Egységtesztek futtatása (test_unit.py)
  run: |
    # Csak a 'test_unit.py' fájlt futtatjuk
    python -m unittest test_unit.py

